/**/controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    franka_robot_state_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

    cartesian_impedance_controller:
      type: franka_impedance_controller/CartesianImpedanceController

/**/cartesian_impedance_controller:
  ros__parameters:
    translational_stiffness: 500.0
    translational_damping: 100.0
    rotational_stiffness: 60.0
    rotational_damping: 6.0
    nullspace_stiffness: 20.0
    translational_clip: 0.06
    rotational_clip: 0.1
    enable_nullspace_joints: false
    q_d_nullspace: [0.0, -0.78540, 0.0, -2.35619, 0.0, 1.57080, 0.78540]


/**/franka_robot_state_broadcaster:
  ros__parameters:
    update_rate: 100  # Hz, up to 1000 Hz