version: '2'

services:
  panda_ros2:
    build:
      context: .
      dockerfile: Dockerfile
      network: "host"
      args:
        - https_proxy=${https_proxy}
        - USER_UID=${USER_UID:?error}
        - USER_GID=${USER_GID:?error}
        - USERNAME=${USERNAME:?error}
    container_name: panda_ros2
    network_mode: "host"
    privileged: true
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ../:/home/${USERNAME}/ros2_ws/src/franka_ros2
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./limits.conf:/etc/security/limits.conf
      # - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - .vscode-server:/home/${USERNAME}/.vscode-server:rwfranka_panda_ros2_bosch
      - .vscode:/home/${USERNAME}/ros2_ws/.vscode:rw
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      TERM: xterm-256color
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856